### ISSUE TITLE
Cannot find module 'require-dir'

### ISSUE THREAD

**Issue by packytagliaferro** [synapticism/wordpress-gulp-bower-sass#10]
I ran gulp after bower install and adding 2 new dependenceis I wanted (Bourbon and Neat). I got this error

`Error: Cannot find module 'require-dir'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/PackyTagliaferro/Sites/SassGulpBowerWP.com/wp-content/themes/gulpfile.js/index.js:6:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)`

**Comment by Annalyn** [comment]
About this issue, I have installed bourbon and neat on my project.  My question is how do I add them on my gulpconfig.js?

I just import them on my styles.scss to make it work, adding them to my gulpconfig.js file is way better,

**Comment by synapticism** [comment]
I haven't used either but I think you need an explicit import in any case. Let me know if you find some other way... but my guess is that I'd have to configure the base repo to include bourbon/neat and I'm trying to keep it as bare bones as possible :)

**Comment by Annalyn** [comment]
I was trying to add it like you added normalize.css.  But then I realized that the normalize that you used is not sass. And Bourbon/Neat has many files and folders inside it.

**Comment by synapticism** [comment]
Ah, I see. Yes, normalize is a bit of a special case. Looks like Bourbon has it's own installer that you may need to use.
